export const SAFETY_KEYWORDS = [
  "golpear",
  "pegar",
  "empujar",
  "herir",
  "matar",
  "cuchillo",
  "sangre",
  "punetazo",
  "patada",
  "ahorcar",
  "quemar",
  "disparar",
  "arma",
  "navaja",
  "moraton",
  "bofetada",
  "agresion",
  "paliza",
  "violencia",
  "abuso",
  "golpes",
  "tirar del pelo",
  "estrangulacion",
  "asfixiar",
  "lesion",
  "hacer dano",
  "culpa",
  "loco",
  "loca",
  "inventas",
  "imaginas",
  "celos",
  "control",
  "revisar movil",
  "contrasena",
  "ubicacion",
  "prohibir",
  "amigos",
  "familia",
  "nadie te quiere",
  "inutil",
  "todo es tu culpa",
  "me provocas",
  "si me dejas me mato",
  "chantaje",
  "amenaza",
  "miedo",
  "terror",
  "aislamiento",
  "ley del hielo",
  "no vales nada",
  "gaslighting",
  "manipulacion",
  "manipular",
  "controlar",
  "obedecer",
  "no salgas",
  "no hables con",
  "no trabajes",
  "no estudies",
  "te vigilo",
  "te espio",
  "te lo mereces",
  "estas loca",
  "estas loco",
  "exageras",
  "no fue para tanto",
  "te lo inventaste",
  "nadie te va a creer",
  "dependes de mi",
  "sin mi no eres nada",
  "quien te va a querer",
  "gritar",
  "humillar",
  "ridiculizar",
  "chantajear",
  "amenazar",
  "intimidar",
  "acoso",
  "acosar",
  "perseguir",
  "posesivo",
  "revisar mensajes",
  "revisar redes",
  "quien te escribe",
  "no te vistas asi",
  "callate",
  "no opines",
  "eres mio",
  "eres mia",
  "solo digo la verdad",
  "es tu problema",
  "si no te gusta",
  "tu te lo buscaste",
  "mira lo que me haces hacer",
  "no aguantas nada",
  "eres una dramatica",
  "eres un dramatico",
  "donde estabas",
  "a ti que te importa",
  "no es asunto tuyo",
  "no tengo que explicarte",
  "no te debo explicaciones",
  "suicidio",
  "suicidar",
  "morir",
  "quitarme la vida",
  "cortarme",
  "pastillas",
  "no quiero vivir",
  "acabar con todo",
  "desaparecer",
  "autolesion",
  "suicidarme",
  "quiero morirme",
  "me quiero morir",
  "colgarme",
  "cortarme las venas",
  "overdosis",
  "sobredosis",
  "abuso sexual",
  "violar",
  "violacion",
  "forzar",
  "obligar",
  "no queria",
  "no consenti",
  "maltrato",
  "maltratar",
  "maltrato psicologico",
  "insultar",
  "coaccion",
  "presion",
  "presionar",
  "obligarme",
  "no me deja ir",
  "me tiene atrapada",
  "me tiene atrapado",
  "no puedo salir",
  "me encierra",
  "me quita el dinero",
  "te voy a matar",
  "te mato",
  "te parto la cara",
  "te rompo",
  "te voy a dar una paliza",
  "te voy a pegar",
  "me las pagaras",
  "relacion toxica",
  "toxico",
  "toxica",
  "pareja violenta",
  "maltratador",
  "maltratadora",
  "le tengo miedo",
  "no me atrevo a dejarlo",
  "no me atrevo a dejarla",
  "me va a hacer algo",
  "no tengo a donde ir",
  "no me deja salir",
  "me prohibe salir",
  "me tiene encerrada",
  "me tiene encerrado",
  "no quiere que salga",
  "voy provocando",
  "vas provocando",
  "no me deja salir de casa",
  "me obliga a quedarme",
  "no puedo ver a mis amigos",
  "no puedo salir con mis amigas",
  "no me deja ver a mi familia",
  "solo puede estar conmigo",
  "tengo que pedir permiso",
  "me controla donde voy",
  "me pide la ubicacion",
  "se enfada si salgo",
  "me castiga si salgo",
  "no me deja tener vida social",
  "me ha alejado de todo el mundo",
  "controla mis horarios",
  "me pone toque de queda",
  "me quita las llaves",
  "no tengo libertad",
  "dependencia emocional",
  "me critica constantemente",
  "me menosprecia",
  "me culpa de todo",
  "me hace dudar",
  "me hace sentir culpable",
  "chantaje emocional",
  "amor condicional",
  "amenaza con dejarme",
  "amenaza con marcharse",
  "me voy si no",
  "te dejo si no",
  "si no haces lo que digo me voy",
  "si no lo haces te dejo",
  "ultimatum",
  "me pone condiciones",
  "kill",
  "kill myself",
  "suicide",
  "hurt myself",
  "cut myself",
  "self-harm",
  "abuse",
  "hit me",
  "beat me",
  "punch",
  "slap",
  "strangle",
  "threaten",
  "control",
  "manipulate",
  "gaslight",
  "worthless",
  "useless",
  "no one loves you",
  "your fault",
  "crazy",
  "isolate",
  "scared",
  "afraid",
  "doesn't let me leave",
  "can't see my friends",
  "keeps me locked",
  "not allowed to go out",
  "tracks my location",
  "toxic relationship",
  "emotional abuse",
  "threatens to leave",
  "emotional blackmail"
];

function normalizeText(text) {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");
}

export function detectSafetyTrigger(messages, { includeAssistant = false } = {}) {
  const textToScan = messages
    .filter((message) => message.role === "user" || (includeAssistant && message.role === "assistant"))
    .map((message) => normalizeText(message.text || ""))
    .join(" ");

  return SAFETY_KEYWORDS.some((keyword) => textToScan.includes(normalizeText(keyword)));
}

export function buildSafetyMessage(language) {
  return language.startsWith("en")
    ? "Possible signs of risk have been detected (in your messages or in the partner's). If you need help, contact 016 or emergency services."
    : "Se han detectado posibles signos de riesgo (en lo que escribes o en lo que dice la pareja). Si necesitas ayuda, contacta con el 016 o con emergencias.";
}
